matrix:
- name: Markdown
  sources:
  - '!.venv/**/*.md|**/*.md'
  default_encoding: utf-8
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .vscode/dictionaries/cpp_terms.txt
    - .vscode/dictionaries/python_terms.txt
    - .vscode/dictionaries/project_words.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
