name: 'Self-hosted build'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    # Dockerfile @Ubuntu 22.04 LTS
    name: Self-hosted Runner
    runs-on: [self-hosted, x64]
    strategy:
      matrix:
        os: [Linux, Windows]
        include:
          - os: Linux
            cmake_preset: ci-linux
          - os: Windows
            cmake_preset: ci-windows

    steps:
    - name: Install basic dependencies on ${{matrix.os}}
      if: matrix.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y cmake ninja-build ccache g++-11 clang-14 gettext

    - name: Install conan package manager
      run: |
        python -m pip install --upgrade pip
        pip --disable-pip-version-check --no-cache-dir install wheel conan

    - name: Create conan default profile
      run: |
        conan profile new --detect --force default > /dev/null
        # enforce new CXX11 ABI
        conan profile update settings.compiler.libcxx=libstdc++11 default
        # C++20 standard, not yet, stick @ 20.04 LTS
        conan profile update settings.compiler.cppstd=20 default
        # clang
        conan profile update settings.compiler=clang

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build dependencies with conan
      run: |
        conan install ${{ github.workspace }} --remote conancenter --build missing --profile default

    - name: Setup ccache Compiler Cache
      if: matrix.os == 'Linux'
      uses: hendrikmuhs/ccache-action@v1.2.2

    - name: CMake configuration
      run: |
        cmake --preset ${{ matrix.cmake_preset }}

    - name: CMake Build
      run: |
        cmake --build --preset ${{ matrix.cmake_preset }}

    - name: Build l10n
      if: matrix.os == 'Linux'
      run: |
        cmake --build --preset ${{ matrix.cmake_preset }} --target l10n

    - name: Run Unit Test
      run: |
        ctest --preset ${{ matrix.cmake_preset }}

    - name: Clean up conan build & sources
      run: |
        conan remove -f "*" --builds
        conan remove -f "*" --src
