name: 'C/C++ Lint'

on:
  pull_request:
    types: [opened, reopened]  # let PR-synchronize events be handled by push events
  push:
    branches: [  main  ]
  workflow_dispatch:

env:
  CONAN_V2_MODE : 1

jobs:
  cpp-linter:
    runs-on: ubuntu-24.04
    steps:
    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y cmake ninja-build ccache clang clang-tools

    - name: Install conan package manager and cpp-linter
      run: |
        python -m pip install --upgrade pip
        pip --disable-pip-version-check --no-cache-dir install wheel conan \
          cpp-linter

    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Github's cache for conan
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-clang-conan-${{ hashFiles('conanfile.txt') }}
        path: |
          ~/.conan

    - name: Setup Github's cache for compiler cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-clang-ccache
        path: |
          ~/.config/ccache
          ~/.cache/ccache

    - name: CMake configuration
      run: |
        cmake --preset ci-linux-clang

    - name: Run cpp-linter (clang format && tidy)
      id: linter
      run: |
        cpp-linter --version=18 --style=file --tidy-checks='' --ignore=build --database=build/ci-linux-clang

    - name: Passed C++ style guide checks?!
      if: steps.linter.outputs.checks-failed > 0
      run: |
        echo "Some files failed the Clang tidy/format checks!"
