name: FOSSA

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  fossa-scan:
    name: Fossa Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: FOSSA analysis
        uses: fossas/fossa-action@main
        with:
          api-key:  ${{ secrets.FOSSA_API_KEY }}
