name: 'Python Lint'

on:
  # pull request only
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # threshold to decide if the test was successful
  PYLINT_THRESHOLD_FAIL: 4  # [0 ... 10.0]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Gather Python files from git
      run: |
        echo "PYTHON_FILES=$(git ls-files '*.py')" >> $GITHUB_ENV
    
    - name: Show files to lint
      run: |
        echo "Python: ${{ env.PYTHON_FILES }}"

    - name: Format Python code
      run: |
        python -m pip install --upgrade pip
        pip --disable-pip-version-check --no-cache-dir install wheel black
        black ${{ env.PYTHON_FILES }}

    - name: Analyzing the Python code
      uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: "${{ env.PYTHON_FILES }}"
        use-pylint: true
        use-pycodestyle: true
        use-flake8: true
        use-black: false
        use-isort: true
        use-mypy: true
        extra-pylint-options: "--fail-under ${{env.PYLINT_THRESHOLD_FAIL}}"
        extra-pycodestyle-options: ""
        extra-flake8-options: ""
        extra-black-options: ""
        extra-isort-options: ""
        extra-mypy-options: ""
