name: 'SpellCheck'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Gather Markdown files from git
      run: echo "MARKDOWN_FILES=$(git ls-files '*.md')" >> $GITHUB_ENV

    - name: Check Spelling
      uses: rojopolis/spellcheck-github-actions@0.24.0
      with:
        config_path: .github/config/spellcheck.yml
        source_files: ${{ env.MARKDOWN_FILES }}
        task_name: Markdown
